name: Create Ephemeral Env CI/CD
on:
  pull_request:
    branches: [ master ]
    types: [opened]

env:
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  BASE_STACK_NAME: ${{ secrets.BASE_STACK_NAME }}
  SAM_BUCKET: ${{ secrets.SAM_BUCKET }}

jobs:
  Build-Deploy-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger frontend workflow
        run: |
          scripts/trigger-frontend-create-env-workflow ianballard \
            ab78d0fa856e483bd3c52d24bb202c587ce0e5fd \
            ianballard \
            serverless-ephemeral-env-frontend-starter \
            "$GITHUB_HEAD_REF"
